version: '{build}'
branches:
  only:
  - master
# clone_folder: c:\projects\cppagent_dev
image:
- Ubuntu1804
- Visual Studio 2019

configuration:
- Release

platform:
- x86

#environment:
#  matrix:
#  - arch: Win32
#  - arch: #does not work, Release|x64 not a valid target

matrix:
  fast_finish: true

# skip unsupported combinations
init:
- cmd: |-
    echo %arch%
    echo %APPVEYOR_BUILD_WORKER_IMAGE%
    echo %generator%
    echo %MSBUILD_FLAGS%
# - sh: sudo apt-get update
# - sh: sudo apt-get --yes install libxml2-dev

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -DAGENT_ENABLE_UNITTESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON -G %generator%
- sh: mkdir build
- sh: cd build
- sh: cmake --version
- sh: cmake .. -DAGENT_ENABLE_UNITTESTS=ON -DCMAKE_VERBOSE_MAKEFILE=ON
    

build:
  project: '{APPVEYOR_BUILD_FOLDER}/build'
  verbosity: minimal
  parallel: true

build_script:
- cmd: |-
    cd %APPVEYOR_BUILD_FOLDER%\build
    cmake --build . --config Release --target ALL_BUILD -- %MSBUILD_FLAGS%
- sh: |-
    cd ${APPVEYOR_BUILD_FOLDER}/build
    cmake --build . --config Release --target all -- -j4

test_script:
- cmd: ctest -C Release --output-on-failure
- sh: ctest

  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - test/
    - cmake/
    - dlib_fix/
    - libxml2_make/
    - agent/
