version: '{build}'
branches:
  only:
    - master
    - /.*master.*/
  
image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS

configuration:
  - Release

platform:
  - x64

cache:
  - c:\.conan\ -> conanfile.py
  - c:\conan\ -> conanfile.py
  - /home/appveyor/.conan -> conanfile.py
  - /Users/appveyor/.conan -> conanfile.py

matrix:
  fast_finish: true
  
init:
  - cmd: |-
      echo %APPVEYOR_BUILD_WORKER_IMAGE%
      echo %MSBUILD_FLAGS%

#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
# - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

before_build:
  - cmd: |-
      if not exist C:\conan mkdir C:\conan
      set CONAN_USER_HOME=C:\conan
      set PATH=C:\Python39-x64\;C:\Python39-x64\Scripts;%PATH%
      pip install conan
      conan export conan/mqtt_cpp
      conan export conan/boost/all boost/1.75.0@
      conan install . -if build --build=missing -pr conan/profiles/vs32 -o run_tests=False
  - sh: |-
      export PATH=$HOME/venv3.9/bin:$PATH
      if [[ $APPVEYOR_BUILD_WORKER_IMAGE = "Ubuntu2004" ]]
      then
        export CONAN_PROFILE=conan/profiles/gcc-appveyor
      elif [[ $APPVEYOR_BUILD_WORKER_IMAGE = "macOS" ]]
      then
        export CONAN_PROFILE=conan/profiles/macos
      else
        echo "*NIX Operating System" $APPVEYOR_BUILD_WORKER_IMAGE "Not Supported"
        exit 99
      fi
      pip install conan
      conan export conan/mqtt_cpp
      conan install . -if build --build=missing -pr $CONAN_PROFILE -o run_tests=False

build:
  verbosity: minimal
  parallel: true

build_script:
  - conan build . -bf build

test_script:
  - cmd: |-
      cd %APPVEYOR_BUILD_FOLDER%/build
      ctest -C Release --output-on-failure
  - sh: |-
      cd ${APPVEYOR_BUILD_FOLDER}/build
      ctest --output-on-failure

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - test/
    - cmake/
    - agent/
    - conan/

