# build docker image

# needs secrets set for these -
#   ACCESS_TOKEN - a github personal access token to access the private repo
#   DOCKERHUB_USERNAME - ladder99 for now
#   DOCKERHUB_TOKEN

name: Build Docker image

# when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# variables - used below, like ${{ env.platforms }}
env:
  # for available platforms see output of a previous run -
  # ie the "Setup Docker BuildX" / "Inspect Builder" section
  # has eg "node_platforms": "linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
  # but the platforms must also be included in the os image chosen -
  # eg the ubuntu image doesn't include linux/arm/v6.
  # platforms: linux/amd64,linux/arm64,linux/arm/v7
  #. for initial testing
  platforms: linux/amd64
  
# a workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains a single job called "build"
  build:
    # the type of runner that the job will run on
    runs-on: ubuntu-latest

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # the QEMU emulator lets us build for arm processors also
      # see https://github.com/docker/setup-qemu-action
      - name: Set up QEMU emulator
        uses: docker/setup-qemu-action@v1

      # see https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # see https://github.com/docker/build-push-action
      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.platforms }}
          secrets: "access_token=${{ secrets.ACCESS_TOKEN }}"

          # docker hub user/repo:tag
          #. add version here
          tags: |
            ladder99/agent2:latest

          # push to docker hub
          push: true
